version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: hospital-api-v2
  app:
    image: hospital-api-v2
    ports:
      - 13000:3000